name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: ['linux', 'darwin', 'windows']
        arch: ['386', 'amd64', 'arm64', 'arm']
        exclude:
          - os: windows
            arch: arm64
          - os: darwin
            arch: arm
          - os: darwin
            arch: '386'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - uses: actions/checkout@v3
      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o dzip
          tar czf dzip-${{ matrix.os }}-${{ matrix.arch }}.tar.gz dzip LICENSE
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dzip-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
