on: ["push", "pull_request"]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
